### ISSUE TITLE
snapshot_receiver not reload friendly

### ISSUE THREAD

**Issue by gitthangbaby** [bartowl/synology-stuff#5]
this one is not reload friendly, and couldn't figure out what port it needs.

* updating certificate for Replication Service
  reloading...
Copyright (c) 2003-2019 Synology Inc. All rights reserved.

Usage: [OPTIONS]
Options are:
-p --port <PORT_NUMBER>: run deamon with the given port

**Comment by bartowl** [comment]
Hi,

Well - this command is exactly what Synology does execute when changing certificate for ReplicationService.

I tried observing this on my Sznology by running following command:
while : ; do ps -fe | grep Replica | grep -v grep; done

and in the meanwhile changing the certificate od ReplicationService to some other domain via DSM GUI.
In the process list could be seen:

root     16818     1  0 Mar14 ?        00:00:00 /var/packages/ReplicationService/target/sbin/ReplicationService-synobtrfsreplicad --port 5566
root     27439 27434  0 15:45 ?        00:00:00 /bin/cp -arp /usr/local/etc/certificate/ReplicationService/snapshot_receiver /usr/local/etc/certificate/ReplicationService/snapshot_receiver.bak
root     16818     1  0 Mar14 ?        00:00:00 /var/packages/ReplicationService/target/sbin/ReplicationService-synobtrfsreplicad --port 5566
root     27439 27434  0 15:45 ?        00:00:00 /bin/cp -arp /usr/local/etc/certificate/ReplicationService/snapshot_receiver /usr/local/etc/certificate/ReplicationService/snapshot_receiver.bak
root     16818     1  0 Mar14 ?        00:00:00 /var/packages/ReplicationService/target/sbin/ReplicationService-synobtrfsreplicad --port 5566
root     27439 27434  0 15:45 ?        00:00:00 /bin/cp -arp /usr/local/etc/certificate/ReplicationService/snapshot_receiver /usr/local/etc/certificate/ReplicationService/snapshot_receiver.bak
root     16818     1  0 Mar14 ?        00:00:00 /var/packages/ReplicationService/target/sbin/ReplicationService-synobtrfsreplicad --port 5566
root     16818     1  0 Mar14 ?        00:00:00 /var/packages/ReplicationService/target/sbin/ReplicationService-synobtrfsreplicad --port 5566
root     16818     1  0 Mar14 ?        00:00:00 /var/packages/ReplicationService/target/sbin/ReplicationService-synobtrfsreplicad --port 5566
root     16818     1  0 Mar14 ?        00:00:00 /var/packages/ReplicationService/target/sbin/ReplicationService-synobtrfsreplicad --port 5566
root     27470 27434  0 15:45 ?        00:00:00 /usr/local/libexec/certificate.d/ReplicationService snapshot_receiver
root     16818     1  0 Mar14 ?        00:00:00 /var/packages/ReplicationService/target/sbin/ReplicationService-synobtrfsreplicad --port 5566
root     16818     1  0 Mar14 ?        00:00:00 /var/packages/ReplicationService/target/sbin/ReplicationService-synobtrfsreplicad --port 5566

**Comment by bartowl** [comment]
Especially this line:
root 27470 27434 0 15:45 ? 00:00:00 /usr/local/libexec/certificate.d/ReplicationService snapshot_receiver

This was called by synology in exact the same way and possibly returned exactly the same error to synology. But it is ignored there, so I guess this is not really an error and could be ignored.

I could implement a redirection to /dev/null, but this does not really solve anything.

**Comment by bartowl** [comment]
Indeed - I have just confirmed this by creating a wrapper. You can test it yourself:
1. rename /usr/local/libexec/certificate.d/ReplicationService to /usr/local/libexec/certificate.d/ReplicationService**.bin**
2. create a bash script under the original location (/usr/local/libexec/certificate.d/ReplicationService) with following content:
```
#!/bin/sh
exec > /tmp/certlog
exec 2>&1
set
exec $0.bin "$@"
```
3. chmod 755 on the script
4. change the certificate for ReplicationService via DSM to any other domain
5. see what got to /tmp/certlog

for me after dumping all environment variables I could find exactly the same output:
Copyright (c) 2003-2019 Synology Inc. All rights reserved.

Usage: [OPTIONS]
Options are:
-p --port <PORT_NUMBER>: run deamon with the given port

6. remember to remove the created bash script and rename /usr/local/libexec/certificate.d/ReplicationService.bin back to /usr/local/libexec/certificate.d/ReplicationService

**Comment by bartowl** [comment]
so - you may really completely ignore this one as it does not do anything...
If this is annoying you, you may want to edit the script to ignore the output of reload wrapper. It is ignored by Synology when doing letsencrypt updates anyway.
